
platform :ios, '13.0'
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'CRIMSDKUIKit_Example' do
  pod 'CRUICore', :path => '../'
  pod 'CRUICoreView', :path => '../'
  pod 'CRUIIM', :path => '../'
  pod 'CRIMSDK', :path => '../'
  pod 'CRUICalling', :path => '../'
  
  pod 'Localize-Swift', '~> 3.2'
  pod 'RxGesture', '~> 4.0.4'
  pod 'ProgressHUD'
  pod 'MMBAlertsPickers'
  pod 'SGCodeTextField'
  pod 'GTSDK', '2.7.1.0-noidfa'
  pod 'Bugly', '2.5.93'
end

post_install do |installer|

 installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
